---
# =============================================================================
# AURA BLOCKCHAIN - STATE SYNC CONFIGURATION
# =============================================================================
# Configure state sync for fast node synchronization
#
# Usage:
#   Configure:    ansible-playbook -i inventory/testnet.yml support_state_sync.yml
#   Single host:  ansible-playbook -i inventory/testnet.yml support_state_sync.yml --limit aura_val1
# =============================================================================

- name: State Sync Configuration
  hosts: all_nodes
  become: true
  gather_facts: true

  vars:
    state_sync_rpc: "{{ public_rpc | default('testnet-rpc.aurablockchain.org:443') }}"
    state_sync_trust_period: "168h0m0s"

  pre_tasks:
    - name: Display state sync info
      ansible.builtin.debug:
        msg: |
          ============================================
          State Sync Configuration: {{ inventory_hostname }}
          ============================================
          RPC: {{ state_sync_rpc }}
          Trust Period: {{ state_sync_trust_period }}
          ============================================

  tasks:
    - name: Get latest block info for state sync
      ansible.builtin.uri:
        url: "https://{{ state_sync_rpc }}/block"
        method: GET
        return_content: true
      register: latest_block
      delegate_to: localhost
      become: false

    - name: Calculate trust height (latest - 2000)
      ansible.builtin.set_fact:
        trust_height: "{{ (latest_block.json.result.block.header.height | int) - 2000 }}"

    - name: Get trust block hash
      ansible.builtin.uri:
        url: "https://{{ state_sync_rpc }}/block?height={{ trust_height }}"
        method: GET
        return_content: true
      register: trust_block
      delegate_to: localhost
      become: false

    - name: Set trust hash
      ansible.builtin.set_fact:
        trust_hash: "{{ trust_block.json.result.block_id.hash }}"

    - name: Display state sync parameters
      ansible.builtin.debug:
        msg: |
          ============================================
          State Sync Parameters
          ============================================
          Trust Height: {{ trust_height }}
          Trust Hash: {{ trust_hash }}
          RPC Servers: {{ state_sync_rpc }},{{ state_sync_rpc }}
          ============================================

          Add to config.toml [statesync] section:
          enable = true
          rpc_servers = "https://{{ state_sync_rpc }},https://{{ state_sync_rpc }}"
          trust_height = {{ trust_height }}
          trust_hash = "{{ trust_hash }}"
          trust_period = "{{ state_sync_trust_period }}"
          ============================================

    - name: Update config.toml with state sync settings
      ansible.builtin.blockinfile:
        path: "{{ node_daemon_home }}/config/config.toml"
        marker: "# {mark} ANSIBLE MANAGED - STATE SYNC"
        insertafter: '^\[statesync\]'
        block: |
          enable = true
          rpc_servers = "https://{{ state_sync_rpc }},https://{{ state_sync_rpc }}"
          trust_height = {{ trust_height }}
          trust_hash = "{{ trust_hash }}"
          trust_period = "{{ state_sync_trust_period }}"
      when: state_sync_enable | default(false)
      notify: Restart node service

  handlers:
    - name: Restart node service
      ansible.builtin.service:
        name: "{{ node_service_name }}"
        state: restarted
